### ISSUE TITLE
Checklist for version 1

### ISSUE THREAD

**Issue by JFrap** [JFrap/KhaanEngine#2]
- [ ] Integrate dependancies to the actual engine (instead of an external library)
- [ ] Get CMake working
- [ ] Add Spot Lights
- [ ] Add Directional Lights
- [ ] Add Shadows
- [ ] Add some sort of external script component
